# Generated by Django 4.0.7 on 2022-10-18 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('C_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(default='ABC', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Employes',
            fields=[
                ('E_id', models.IntegerField(primary_key=True, serialize=False)),
                ('F_name', models.CharField(default='ABC', max_length=200)),
                ('Email', models.CharField(default='xyz@gmail.com', max_length=200)),
                ('L_name', models.CharField(default='ABC', max_length=200)),
                ('profile_pic', models.ImageField(upload_to='uploads/')),
                ('C_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.company')),
            ],
        ),
    ]
