# Generated by Django 4.0.7 on 2022-10-18 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employes',
            name='profile_pic',
            field=models.CharField(max_length=400),
        ),
    ]
