# Generated by Django 4.0.7 on 2022-10-18 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_alter_employes_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employes',
            name='profile_pic',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
